version: "3.8"

services:
  media-scheduler:
    build: .
    container_name: media-scheduler
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    working_dir: /app
